id: AEEF94713
base_file: f1886.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:54:20.832172
  last_modified_at: 2022-05-31 06:54:20.832179
